networks:
  proxy:
    driver: bridge

services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - '4000:4000'
    depends_on:
      - db
  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    networks:
      - proxy
    environment:
      MYSQL_DATABASE: 'nft-selections'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
