networks:
  proxy:
    driver: bridge

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: app
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    networks:
      - proxy
    environment:
      MYSQL_DATABASE: 'nft-selections'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD  -e 'SHOW databases'"
      interval: 5s
      retries: 5
      start_period: 5s
